### ISSUE TITLE
Filmes react

### ISSUE THREAD

**Issue by julianosilva94** [jeanbauer/puc-react#1]
https://github.com/julianosilva94/react-movies

**Comment by jeanbauer** [comment]
Muito obrigado Juliano! Ontem fui atualizar o repo aqui mas parece que derrubamos a API :/

só uma observação, cuidado para não repetir a fonte de informação nos teus componentes, por exemplo no Card.js tu acaba internalizando as props ao state:

```
      this.state = {
        title: props.title,
        img: props.img
      };
```

Fazendo isso em uma escala maior, ficará dificil saber qual é a fonte da verdade das informações, principalmente quando tu tiveres que alterar o valor da prop/state.

_Fonte_: https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html
